config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :services
  resources :customers
  resources :parkings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :products
  get 'home/index'

  resources :products
  get 'home/index'

root 'home#index'
end

app/models/parking.rb
class Parking < ActiveRecord::Base
     has_many :rating
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update, :destroy]

  # GET /parkings
  # GET /parkings.json
  def index
    @parkings = Parking.all
  end

  # GET /parkings/1
  # GET /parkings/1.json
  def show
  end

  # GET /parkings/new
  def new
    @parking = Parking.new
  end

  # GET /parkings/1/edit
  def edit
  end

  # POST /parkings
  # POST /parkings.json
  def create
    @parking = Parking.new(parking_params)

    respond_to do |format|
      if @parking.save
        format.html { redirect_to @parking, notice: 'Parking was successfully created.' }
        format.json { render :show, status: :created, location: @parking }
      else
        format.html { render :new }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parkings/1
  # PATCH/PUT /parkings/1.json
  def update
    respond_to do |format|
      if @parking.update(parking_params)
        format.html { redirect_to @parking, notice: 'Parking was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking }
      else
        format.html { render :edit }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkings/1
  # DELETE /parkings/1.json
  def destroy
    @parking.destroy
    respond_to do |format|
      format.html { redirect_to parkings_url, notice: 'Parking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking
      @parking = Parking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_params
      params.require(:parking).permit(:name, :address, :contact, :telephone, :schedule, :price, :availability, :comments, :image, :active)
    end
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/_form.html.erb
<%= simple_form_for(@parking) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :contact %>
    <%= f.input :telephone %>
    <%= f.input :schedule %>
    <%= f.input :price %>
    <%= f.input :availability %>
    <%= f.input :comments %>
    <%= f.input :image %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<h1>Editing Parking</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking %> |
<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parkings Listing</h1> 

<table>
  <thead border="1">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Contact</th>
      <th>Telephone</th>
      <th>Schedule</th>
      <th>Price</th>
      <th>Availability</th>
      <th>Comments</th>
      <th>Image</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody border=1> 
    <% @parkings.each do |parking| %>
      <tr>
        <td><%= parking.name %></td>
        <td><%= parking.address %></td>
        <td><%= parking.contact %></td>
        <td><%= parking.telephone %></td>
        <td><%= parking.schedule %></td>
        <td><%= parking.price %></td>
        <td><%= parking.availability %></td>
        <td><%= parking.comments %></td>
        <td><%= parking.image %></td>
        <td><%= parking.active %></td>
        <td><%= link_to 'Show', parking %></td>
        <td><%= link_to 'Edit', edit_parking_path(parking) %></td>
        <td><%= link_to 'Destroy', parking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking', new_parking_path %>

app/views/parkings/new.html.erb
<h1>New Parking</h1>

<%= render 'form' %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parking.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @parking.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @parking.contact %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @parking.telephone %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @parking.schedule %>
</p>

<p>
  <strong>Price:</strong>
  <%= @parking.price %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @parking.availability %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @parking.comments %>
</p>

<p>
  <strong>Image:</strong>
  <%= @parking.image %>
</p>

<p>
  <strong>Active:</strong>
  <%= @parking.active %>
</p>

<%= link_to 'Edit', edit_parking_path(@parking) %> |
<%= link_to 'Back', parkings_path %>